Reason: final commit

diff --git a/main b/main
--- a/main
+++ b/main
@@ -9,7 +9,7 @@ parc=`jq -r '.parcellation' config.json`
 [ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" && exit 1;
 echo $FREESURFER_LICENSE > license.txt
 
-if [ ! -f ${parc}.nii.gz ]; then
+if [ ! -f ${parc}+aseg.nii.gz ]; then
   time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/freesurfer-mini:6.0.1 bash -c "mri_convert ${fsdir}/mri/${parc}+aseg.mgz ./${parc}+aseg.nii.gz"
 fi
 
@@ -21,4 +21,8 @@ if [ ! -f rois.csv ]; then
 	time singularity exec -e docker://brainlife/mcr:r2019a ./compiled/parcRoiStats
 fi
 
-[ ! -f whole_brain.csv ||  ! -f rois.csv ] && echo "output missing" && exit 1 || echo "complete" && mkdir -p ./output/ && mv *.csv ./output/ && exit 0
+if [ ! -f whole_brain.csv ] || [ ! -f rois.csv ]; then
+	echo "output missing" && exit 1
+else
+	echo "complete" && mkdir -p ./output/ && mv *.csv ./output/ && rm -rf *.nii.gz && exit 0
+fi
