Reason: final commits

diff --git a/main b/main
--- a/main
+++ b/main
@@ -21,11 +21,11 @@ if [ ! -f whole_brain.csv ]; then
 	time singularity exec -e docker://brainlife/freesurfer-stats:1.2 ./create_data_csv.py
 fi
 
-#if [ ! -f whole_brain.csv ] || [ ! -f rois.csv ]; then
-#	echo "output missing" && exit 1
-#else
-#	echo "complete" && mkdir -p ./parc-stats/ && mv *.csv ./parc-stats/ && rm -rf *.nii.gz
-#	echo "{\"tags\": [\"${parc}\"]}" > product.json
-#   	exit 0
-#
-#fi
+if [ ! -f whole_brain.csv ] || [ ! -f rois.csv ]; then
+	echo "output missing" && exit 1
+else
+	echo "complete" && mkdir -p ./parc-stats/ && mv *.csv ./parc-stats/ && rm -rf *.nii.gz
+	echo "{\"tags\": [\"${parc}\"]}" > product.json
+   	exit 0
+
+fi
