Reason: updates to include ROI data

diff --git a/main b/main
--- a/main
+++ b/main
@@ -1,10 +1,24 @@
 #!/bin/bash
-
-#PBS -l nodes=1:ppn=1
-#PBS -l vmem=16gb
-#PBS -l walltime=0:10:00
-#PBS -N app-freesurer-stats
+#PBS -l nodes=1:ppn=4,vmem=100gb,walltime=00:45:00
+#PBS -N roi-stats
 #PBS -V
 
-time singularity exec -e docker://brainlife/freesurfer-stats:latest ./create_data_csv.py
+fsdir=`jq -r '.freesurfer' config.json`
+parc=`jq -r '.parc' config.json`
 
+[ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" && exit 1;
+echo $FREESURFER_LICENSE > license.txt
+
+if [ ! -f ${parc}.nii.gz ]; then
+  time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/freesurfer-mini:6.0.1 bash -c "mri_convert ${fsdir}/mri/${parc}.mgz ./${parc}.nii.gz"
+fi
+
+if [ ! -f whole_brain.csv ]; then
+	time singularity exec -e docker://brainlife/freesurfer-stats:latest ./create_data_csv.py
+fi
+
+if [ ! -f rois.csv ]; then
+	time singularity exec -e docker://brainlife/mcr:r2020a ./ROI/parcRoiStats
+fi
+
+[ ! -f whole_brain.csv ||  ! -f rois.csv ] && echo "output missing" && exit 1 || echo "complete" && mkdir -p ./output/ && mv *.csv ./output/ && exit 0
