Reason: initial commits for subcort segmentation

diff --git a/main b/main
--- a/main
+++ b/main
@@ -1,31 +1,25 @@
 #!/bin/bash
 #PBS -l nodes=1:ppn=4,vmem=29gb,walltime=00:30:00
-#PBS -N app-freesurfer-stats
+#PBS -N app-freesurfer-stats-subcortical
 #PBS -V
-
-fsdir=`jq -r '.freesurfer' config.json`
-parc=`jq -r '.parcellation' config.json`
 
 [ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" && exit 1;
 echo $FREESURFER_LICENSE > license.txt
 
-if [ ! -f ${parc}+aseg.nii.gz ]; then
-  time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/freesurfer-mini:6.0.1 bash -c "mri_convert ${fsdir}/mri/${parc}+aseg.mgz ./${parc}+aseg.nii.gz"
-fi
+mkdir -p parc-stats
 
-if [ ! -f whole_brain.csv ]; then
+time singularity exec -e docker://brainlife/fsl:5.0.9 ./handle_scaling.sh
+
+[ ! -f subcort_cols.txt ] && time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/freesurfer:6.0.0 ./subcort-stats.sh
+
+if [ ! -f ./parc-stats/aseg_nodes.csv ]; then
 	time singularity exec -e docker://brainlife/freesurfer-stats:1.2 ./create_data_csv.py
 fi
 
-if [ ! -f rois.csv ]; then
-	time singularity exec -e docker://brainlife/mcr:r2019a ./compiled/parcRoiStats
-fi
-
-if [ ! -f whole_brain.csv ] || [ ! -f rois.csv ]; then
-	echo "output missing" && exit 1
+if [ ! -f ./parc-stats/aseg_nodes.csv ]; then
+	echo "output missing"
+	#exit 1
 else
-	echo "complete" && mkdir -p ./parc-stats/ && mv *.csv ./parc-stats/ && rm -rf *.nii.gz
-	echo "{\"tags\": [\"${parc}\"]}" > product.json
-   	exit 0
-
+	echo "complete" && mkdir -p raw && mv *.txt *.csv *.sum ./raw/ && rm -rf *.nii.gz
+   	#exit 0
 fi
